### ISSUE TITLE
Problem during configuration

### ISSUE THREAD

**Issue by Paul-Vdp** [cbeyls/MediaSession2MQTT#3]
I got it iinstalled on a Chromecast with Google TV. One problem : during initial configuration, I can adapt every option except for the mqtt server's IP. When I enter this, I get thrown out of the app, and on re-entering it is clear that the address has not been retained.
So I don't get anywhere ...
Thoughts ?

**Comment by cbeyls** [comment]
My apologies, it looks like the latest release is broken because of a behavior change in the latest version of the KMQTT library. I'll publish a new release later today, or you can use release 1.1.0 in the meantime.

**Comment by Paul-Vdp** [comment]
Thank you @cbeyls for fixing this so fast.
I got through the configuration without any problem this time. So far the good news ...

Alas ... I could test it only briefly, but hit upon 2 problems :
1) I could see mqtt being updated with several of my media apps, but with at least two others - notably the ones I mainly use :-( -  nothing was happening. I am referring to the 'TV Vlaanderen' & the 'Streamz' apps. Is there a workaround for, or do these apps simply cannot be monitored this way ?
2) I could not find any proof that the 'Home Assistant MQTT Discovery' works, because I could not find any device or entity being created automatically. Maybe because I do not know exactly what or where to look for ?

**Comment by cbeyls** [comment]
Unfortunately many apps don't integrate properly with MediaSession, and there is nothing I can do about it because this API is the only way to monitor playback state from the outside. And also, as mentioned in the README, many apps report the playback state but not the content being played. The ones I'm using that work best are Youtube and VLC.

When configuring the MQTT integration in Home Assistant, make sure you check the box named "Enable discovery". You can re-configure the integration later if needed.
As soon as the app connects to the broker, it will publish the configuration and a new device named "MediaSession2MQTT 1" will appear in Home Assistant, along with its 3 sensors. I tested with the latest version and can confirm it still works.

**Comment by Paul-Vdp** [comment]
I was afraid you were going to confirm my hunch about these apps lacking the mediasession api, and that nothing can be done about it - at least not by you or I ...

On the other hand: I cannot get the autodiscovery to work. I double-checked all the relevant settings, then restarted everything just to be sure - but still no device or entities are being created. I can see the mqtt messages arrive in the database when I start playing e.g. on youtube, but even then and there no corresponding mqtt homeassistant topics are created that would represent the entities.
Anything I can do/test/check ?
